---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qianzhikang.
--- DateTime: 2023/4/27 15:50
--- 判断用户是否具有秒杀资格
--- 参数：优惠券id
local voucherId = ARGV[1]
--- 参数：用户id参数
local userId = ARGV[2]
--- 订单id
local orderId = ARGV[3]

--- key： 库存key
local stockKey = 'seckill:stock:' .. voucherId
--- key: 订单key
local orderKey = 'seckill:order:' .. voucherId

--- 脚本业务
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
--- 判断当前用户是否存在在set集合中
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
--- 扣减库存
redis.call('incrby', stockKey, -1)
--- 下单保存id
redis.call('sadd', orderKey, userId)
return 0



